rootProject.name = 'emoticons'

include '1.7.10:forge'
include '1.7.10:ornithe'
include '1.8.9:forge'
include '1.8.9:ornithe'
include '1.9.4:forge'
include '1.9.4:ornithe'
include '1.10.2:forge'
include '1.10.2:ornithe'
include '1.11.2:ornithe'
include '1.12.2:forge'
include '1.12.2:ornithe'
include '1.13.2:ornithe'
include '1.14.4:fabric'
include '1.14.4:ornithe'
