pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Ornithe'
            url = 'https://maven.ornithemc.net/releases'
        }
        maven {
            name = 'OrnitheSnapshots'
            url = 'https://maven.ornithemc.net/snapshots'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'WagYourTailReleases'
            url = 'https://maven.wagyourtail.xyz/releases'
        }
        maven {
            name = 'WagYourTailSnapshots'
            url = 'https://maven.wagyourtail.xyz/snapshots'
        }
    }
}

rootProject.name = 'emoticons'

include '1.7.10:forge'
include '1.7.10:ornithe'
include '1.8.9:forge'
include '1.8.9:ornithe'
include '1.9.4:forge'
include '1.9.4:ornithe'
include '1.10.2:forge'
include '1.10.2:ornithe'
include '1.11.2:forge'
include '1.11.2:ornithe'
include '1.12.2:forge'
include '1.12.2:ornithe'
include '1.13.2:ornithe'
include '1.14.4:fabric'
include '1.14.4:ornithe'
