plugins {
	id 'maven-publish'
	id 'fabric-loom' version '1.17-SNAPSHOT'
	id 'ploceus' version '1.17-SNAPSHOT'
}

base {
	archivesName = project.archives_base_name
}
version = "${project.version}+mc${project.minecraft_version}"
group = project.maven_group

ploceus {
	setIntermediaryGeneration(2)
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	mappings ploceus.featherMappings(project.feather_build)

	ploceus.dependOsl(project.osl_version)
	implementation 'java3d:vecmath:1.5.2'
	include 'java3d:vecmath:1.5.2'
}

processResources {
	inputs.property 'version', version

	filesMatching('fabric.mod.json') {
		expand 'version': version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.compilerArgs.add('-Xlint:-options')
}

java {
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
	withSourcesJar()
}
jar {
	from('../LICENSE.txt') {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

}

sourceSets.main.resources {
	exclude 'assets/mclib/**'
}
