plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.1'
}

group = 'mchorse.emoticons'
version = project.mod_version

base {
    archivesName = 'emoticons'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

repositories {
    mavenCentral()
}

unimined.minecraft {
    version "1.7.10"

    mappings {
        searge()
        mcp("stable", "12-1.7.10")
    }

    minecraftForge {
        loader "10.13.4.1614-1.7.10"
    }
}

dependencies {
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "1.7.10"

    filesMatching("mcmod.info") {
        expand "version": project.version, "mcversion": "1.7.10"
    }
}
