plugins {
	id 'java'
	id 'xyz.wagyourtail.unimined' version '1.4.1'
}

group = project.maven_group
version = "${project.version}+mc${project.minecraft_version}"

base {
	archivesName = project.archives_base_name
}

java {
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
}

repositories {
	mavenCentral()
}

unimined.minecraft {
	version project.minecraft_version

	mappings {
		intermediary()
		yarn(project.yarn_build as int)
	}

	fabric {
		loader project.loader_version
	}
}

dependencies {
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation 'java3d:vecmath:1.5.2'
	include 'java3d:vecmath:1.5.2'
}

processResources {
	inputs.property 'version', version

	filesMatching('fabric.mod.json') {
		expand 'version': version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
}

[tasks.named('runClient'), tasks.named('runServer')].each {
	it.configure {
		doFirst {
			def classesDir = sourceSets.main.output.classesDirs.singleFile
			def resourcesDir = sourceSets.main.output.resourcesDir
			jvmArgs "-Dfabric.classPathGroups=${resourcesDir}${File.pathSeparator}${classesDir}"
		}
	}
}

jar {
	from('../LICENSE.txt') {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
